name: Close Pull Request

on:
  pull_request_target:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: superbrothers/close-pull-request@v3
      with:
        comment: "We do not accept PRs. If you have any questions, please contact us via Telegram (https://t.me/joinchat/AAAAAEhFTR9JV3Vf6NAWZw)."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
